# Generated by Django 3.1.3 on 2021-05-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_alter_lecture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
